version: '3.7'
services:
  frontend:
    container_name: wms-frontend
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: wms-backend
    build:
      context: ./backend
      args:
        GL_NPM_TOKEN: ${GL_NPM_TOKEN}
    user: node
    command: bash -c "npx prisma migrate deploy && npx prisma db seed && npm run start"
    env_file:
      - .env.docker
    depends_on:
      - opensearch
      - redis
    ports:
      - 3001:3000
    networks:
      - wms-network
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:1.2.4
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    env_file:
      - .env.docker
    networks:
      - wms-network
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - wms-network

networks:
  wms-network:

volumes:
  nodemodules:
  opensearch-data1:
