version: '3.7'
services:
  db:
    container_name: db
    hostname: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    networks:
      - wms-network
networks:
  wms-network:

