-- AlterTable
ALTER TABLE `InventoryRequest` MODIFY `type` ENUM('PURCHASE', 'RETURN', 'ADJUSTMENT', 'RECEIPT', 'TRANSFER', 'RETURN_IN') NOT NULL;

-- AlterTable
ALTER TABLE `Reason` MODIFY `type` ENUM('RETURN', 'ADJUSTMENT', 'RETURN_IN', 'TRANSFER') NOT NULL;
