export enum DATE_FORMAT {
  PURCH_ORDER = 'DD MMMM YYYY',
  RECEIPTS_FROM = 'DD MMM',
  RECEIPTS_TO = 'DD MMMM YY',
  GRN = 'DD/MM/YYYY',
  GRN_DISPLAY = 'DD MMMM YYYY',
  TRANSFERS_CREATE = 'DD MMM',
  TRANSFERS_CONFIRMED = 'DD MMM YY',
  ADJUSTMENTS = 'MMMM DD, YYYY',
  TRANSFER = 'MMMM DD, YYYY'
}

export enum DATE_FORMAT_FILTERS {
  COMMON = 'DD/MM/YYYY'
}

export enum TIME_FORMAT {
  ADJUSTMENTS = 'LT',
  TRANSFER = 'LT'
}
